### ISSUE TITLE
Current version seems to have a problem with apache commons

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#10]
This version works

    def sbtKarafPackaging = ProjectRef(
      uri("git://github.com/wav/osgi-tooling.git#7e952d7569d540d3711a3ee31b8b75135db12d49"),
      "sbt-karaf-packaging")

This version does not (version mentioned on your wiki)

    def sbtKarafPackaging = ProjectRef(
        uri("git://github.com/wav/osgi-tooling.git#e390f0b948586e2ea3e6d18b2b44dd5be3669508"),
        "sbt-karaf-packaging")

...

    G:\home\projects\universe\browser\application\apps\base_osgi3>sbt clean compile
    osgiBundle featuresFile
    Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
    port was removed in 8.0
    [info] Loading project definition from C:\Users\user\.sbt\0.13\staging\3effabd4e
    7aba974f2e8\sbt-osgi\project
    [info] Loading project definition from C:\Users\user\.sbt\0.13\staging\db5bca1a5
    71d5c58d499\osgi-tooling\project
    [info] Loading project definition from G:\home\projects\universe\browser\applica
    tion\apps\base_osgi3\project
    [info] Set current project to base_osgi3 (in build file:/G:/home/projects/univer
    se/browser/application/apps/base_osgi3/)
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
    s.
    [success] Total time: 0 s, completed 06-Oct-2015 09:31:51
    [info] Updating {file:/G:/home/projects/universe/browser/application/apps/base_o
    sgi3/}base_osgi3...
    [info] Resolving jline#jline;2.12.1 ...
    [info] Done updating.
    [info] Compiling 6 Scala sources to G:\home\projects\universe\browser\applicatio
    n\apps\base_osgi3\target\scala-2.11\classes...
    [warn] there was one feature warning; re-run with -feature for details
    [warn] one warning found
    [success] Total time: 8 s, completed 06-Oct-2015 09:31:59
    [success] Total time: 1 s, completed 06-Oct-2015 09:32:00
    java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
            at wav.devtools.karaf.packaging.Util$.write(Util.scala:52)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    uresFileTask$1.apply(Defaults.scala:19)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    uresFileTask$1.apply(Defaults.scala:18)
            at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
            at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
            at sbt.std.Transform$$anon$4.work(System.scala:63)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
            at sbt.Execute.work(Execute.scala:235)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
    tions.scala:159)
            at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
    1)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
    java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
    .java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at wav.devtools.karaf.packaging.Util$.write(Util.scala:52)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    uresFileTask$1.apply(Defaults.scala:19)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    uresFileTask$1.apply(Defaults.scala:18)
            at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
            at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
            at sbt.std.Transform$$anon$4.work(System.scala:63)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
            at sbt.Execute.work(Execute.scala:235)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
    tions.scala:159)
            at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
    1)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
    java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
    .java:617)
            at java.lang.Thread.run(Thread.java:745)
    [error] (*:featuresFile) java.lang.NoClassDefFoundError: org/apache/commons/io/F
    ileUtils
    [error] Total time: 1 s, completed 06-Oct-2015 09:32:00

    G:\home\projects\universe\browser\application\apps\base_osgi3>sbt clean compile
    osgiBundle featuresFile

**Comment by wav** [comment]
This looks like a plugin cache issue with sbt. Try deleting the plugin related cache and artifacts. For example

```bash
# from ./clean.sh
rm -Rf ~/.ivy2/local/wav.devtools/* \ 
	~/.sbt/0.13/{dependency,staging}
```

**Comment by PhilAndrew** [comment]
Correct thanks!
