### ISSUE TITLE
My base osgi project using osgi-tooling to demonstrate current problems

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#12]
Hi, since I'm using your project and came up with bugs as I was mentioning before, I should share my project with you so you can see what problem I have.

The project is located here:
https://github.com/PhilAndrew/base_osgi

The main problems are "worked-around" by the code at the bottom of the build.sbt file. 

Problem 1) dependency=true and start=false, this code removes that from the features file.
Problem 2) Some items had to be excluded from the features file in order for it to load in Karaf, see excludedFromKaraf.
Problem 3) dependencies sometimes end with / or multiple // ... remove these. Although this does not seem to be a problem that causes Karaf any problem.

Thanks, Philip

**Comment by wav** [comment]
I'm planning to do some work this weekend on this. I'll see what I can do about making your build file *much* nicer.

Cheers for taking the time to do this.

**Comment by PhilAndrew** [comment]
Thanks! Problem 2), I haven't even put any thought into why this is the case, I just had to get it working and taking these out made it work then get back to coding. 
The main purpose of this OSGi project is to allow Blueprint and Apache Camel and Akka to be working together with your tooling which is the base OSGi project I wish to use for Microservices using Akka as the transport via Akka remoting.

**Comment by PhilAndrew** [comment]
Thanks very much for the recent changes to base-osgi! The only problem is that IntelliJ IDEA does not like the sbt file anymore and cannot create a project from this sbt file.

**Comment by PhilAndrew** [comment]
I tried to run it, the base_osgi, this afternoon and had this error, can you suggest why?

2015-10-14 16:27:16,683 | ERROR | pool-84-thread-1 | BlueprintContainerImpl           | 12 - org.apache.aries.blueprint.core - 1.4.4 | Unable to start blueprint container for bundle default.base_osgi/1.0.0
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to instantiate components
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:686)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:377)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:269)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:294)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:263)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:253)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[21:org.apache.aries.util:1.1.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[21:org.apache.aries.util:1.1.1]
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1179)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:730)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:485)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4544)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2166)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1189)[8:org.apache.karaf.features.core:4.0.2]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:836)[8:org.apache.karaf.features.core:4.0.2]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1079)[8:org.apache.karaf.features.core:4.0.2]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:975)[8:org.apache.karaf.features.core:4.0.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: org/apache/camel/impl/DefaultCamelContext
	at java.lang.Class.getDeclaredConstructors0(Native Method)[:1.8.0_51]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)[:1.8.0_51]
	at java.lang.Class.getConstructors(Class.java:1651)[:1.8.0_51]
	at org.apache.aries.blueprint.container.BeanRecipe.findMatchingConstructors(BeanRecipe.java:509)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:327)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:806)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_51]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:247)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[12:org.apache.aries.blueprint.core:1.4.4]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:682)[12:org.apache.aries.blueprint.core:1.4.4]
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.impl.DefaultCamelContext not found by default.base_osgi [672]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)[org.apache.felix.framework-5.2.0.jar:]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_51]
	... 38 more

**Comment by PhilAndrew** [comment]
Can you tell me what steps you take to make base_osgi deploy? eg, feature:install camel-blueprint etc? as I am having trouble trying to deploy it.

**Comment by wav** [comment]
This is what I do in the karaf console:

```bash
feature:uninstall -s {name of project feature}
feature:repo-remove {path to project xml || name of feature repo}
feature:repo-add {path to project xml}
feature:install -s {name of project feature}
```

The feature file will contain a "project feature" with all the bundles from `libraryDependencies` in the "compile" configuration as bundles and the `featuresRequired`. This means nothing extra needs to be installed in `karaf` it's all defined in your project feature.

I did find that the project bundle in `base_osgi` doesn't start correctly, it prints a message but doesn't finish starting.

**Comment by wav** [comment]
Here's the features file

```
<features xmlns="http://karaf.apache.org/xmlns/features/v1.3.0" name="base_osgi">
  <repository>mvn:org.apache.karaf.features/standard/4.0.1/xml/features</repository>
  <repository>mvn:org.apache.camel.karaf/apache-camel/2.16.0/xml/features</repository>
  <feature description="base_osgi" version="1.0.0" name="base_osgi">
    <bundle>mvn:com.typesafe.akka/akka-actor_2.11/2.3.10</bundle>
    <feature dependency="true" prerequisite="true">log</feature>
    <bundle>mvn:com.typesafe.akka/akka-camel_2.11/2.3.10</bundle>
    <bundle>mvn:org.scala-lang/scala-library/2.11.7</bundle>
    <feature dependency="true" prerequisite="true">camel-blueprint</feature>
    <feature dependency="true" prerequisite="true">camel-weather</feature>
    <bundle>wrap:mvn:org.json/json/20140107$Bundle-SymbolicName=json&amp;Bundle-Version=20140107</bundle>
    <bundle>mvn:com.typesafe.akka/akka-osgi_2.11/2.3.10</bundle>
    <bundle>wrap:mvn:org.uncommons.maths/uncommons-maths/1.2.2a</bundle>
    <bundle>file:/Users/wassim/base_osgi/target/scala-2.11/base_osgi_2.11-1.0.jar</bundle>
    <feature dependency="true" prerequisite="true">aries-blueprint</feature>
    <bundle>mvn:com.typesafe.akka/akka-slf4j_2.11/2.3.10</bundle>
    <bundle>wrap:mvn:jfree/jfreechart/1.0.8a</bundle>
    <bundle>mvn:com.google.protobuf/protobuf-java/2.5.0</bundle>
    <bundle>mvn:io.netty/netty/3.8.0.Final</bundle>
    <feature dependency="true" prerequisite="true">scr</feature>
    <bundle>mvn:com.typesafe/config/1.2.1</bundle>
    <bundle>mvn:com.typesafe.akka/akka-remote_2.11/2.3.10</bundle>
    <feature dependency="true" prerequisite="true">wrap</feature>
    <bundle>wrap:mvn:jfree/jcommon/1.0.12</bundle>
  </feature>
</features>
```

And here's what it looks like

```
ID | State       | Lvl | Version                            | Name
----------------------------------------------------------------------------------------------------------------------------------------
44 | Active      |  80 | 2.16.0                             | camel-catalog
45 | Active      |  80 | 2.16.0                             | camel-core
55 | Active      |  80 | 2.2.6.1                            | Apache ServiceMix :: Bundles :: jaxb-impl
58 | Active      |  80 | 3.1.4                              | Stax2 API
59 | Active      |  80 | 4.4.1                              | Woodstox XML-processor
60 | Active      |  80 | 2.5.0                              | Protocol Buffer Java API
61 | Active      |  80 | 2.3.10                             | com.typesafe.akka.actor
62 | Active      |  80 | 2.3.10                             | com.typesafe.akka.camel
63 | Active      |  80 | 2.3.10                             | com.typesafe.akka.osgi
64 | Active      |  80 | 2.3.10                             | com.typesafe.akka.remote
65 | Active      |  80 | 2.3.10                             | com.typesafe.akka.slf4j
66 | Active      |  80 | 1.2.1                              | com.typesafe.config
67 | GracePeriod |  80 | 1.0                                | base_osgi
68 | Active      |  80 | 20140107                           | json
69 | Active      |  80 | 3.8.0.Final                        | The Netty Project
70 | Active      |  80 | 2.11.7.v20150622-112736-1fbce4612c | Scala Standard Library
71 | Active      |  80 | 0                                  | wrap_file__Users_wassim_.m2_repository_jfree_jcommon_1.0.12_jcommon-1.0.12.jar
72 | Active      |  80 | 0                                  | wrap_file__Users_wassim_.m2_repository_jfree_jfreechart_1.0.8a_jfreechart-1.0.8a.jar
73 | Active      |  80 | 0                                  | wrap_file__Users_wassim_.m2_repository_org_uncommons_maths_uncommons-maths_1.2.2a_unc
```

**Comment by PhilAndrew** [comment]
Thanks that's very helpful.

**Comment by wav** [comment]
I'll create a separate issue for the IntelliJ problem.

Since you're using this, I should share my thoughts on this project (I'm going off topic here!).

I've found that I keep tripping up on the problem of setting up project dependencies and deploying a good features file my self. When deploying features, I find that in order for it to be robust you need to start karaf from a clean state. If this is truly the case, I think that using a `bnd` and `bndrun` file like seen in http://bndtools.org is simpler. I'm steering towards this approach.

There's actually an implementation here https://github.com/doolse/sbt-osgi-felix for sbt. It uses the felix resolver so it should be able to provide good resolver errors now if not in the future. I have not used it personally yet and it doesn't appear to have too many tests. But I feel it's a much better approach and more in line with where OSGi appears to be going (see http://enroute.osgi.org) than using a features file.

Since you're actively using OSGi at the moment it may be in your interests to have a look at that project.

**Comment by PhilAndrew** [comment]
Yes I find that karaf gets into a bad state easily and I have to delete it and create a new one, that's not really a problem for when things are working but getting the project into the working state is a bit of work and time and a bit frustrating since I don't want to learn too much about osgi, karaf, I just want the ability to deploy into an osgi container which can run blueprint and Akka, which I gather can be any osgi container if I have the right dependencies. 

What you showed, sbt-osgi-felix looks more likely not to run into the bad state problem since it can run in embedded more or in the container. Need to be able to run in container because I don't want lots of jvms running and I want efficient communication between my services.

**Comment by wav** [comment]
IntelliJ should be happy now. Remember to clear your plugin cache.

**Comment by PhilAndrew** [comment]
Thanks. If your interested I'm trying to get my Akka OSGI Camel Blueprint working again using that other library, you can read here - https://github.com/doolse/sbt-osgi-felix-test/issues/1 if you feel like helping.

**Comment by PhilAndrew** [comment]
Now I switched back to the Karaf project, my base_osgi project just makes my Karaf go crazy and I don't know why. I'll try to find out by cutting down the features until something works.

**Comment by PhilAndrew** [comment]
Ok by a process of elimination and no reasoning at all I find that this line in the build.sbt

FeatureID("org.apache.karaf.features", "standard", "4.0.1"),

Makes Karaf go nuts. So I take it out, still project only starts the activator but that's a good first step.

**Comment by PhilAndrew** [comment]
I don't know why the blueprint and akka is not working...

**Comment by wav** [comment]
I'll see if i can have a look tonight. You should be able to verify that blueprint works by itself by using an empty project (no code just a blueprint xml) with the camel and blueprint and log features.

See  http://camel.apache.org/using-osgi-blueprint-with-camel.html

I expect that and not much else should display log messages when the project bundle/feature  starts.

**Comment by PhilAndrew** [comment]
So strange, last night my sbt build was working, today its giving

    [info] Set current project to base_osgi (in build file:/D:/home/projects/base_os
    gi/)
    java.lang.RuntimeException: The following features could not be resolved: Set(De
    pendency(aries-blueprint,0.0.0,true,true), Dependency(wrap,0.0.0,true,true), Dep
    endency(log,0.0.0,true,true), Dependency(scr,0.0.0,true,true))
            at scala.sys.package$.error(package.scala:27)
            at wav.devtools.karaf.packaging.Resolution$.mustResolveFeatures(Resoluti
    on.scala:52)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    ureDependencies$1.apply(Defaults.scala:150)
            at wav.devtools.sbt.karaf.packaging.KarafPackagingDefaults$$anonfun$feat
    ureDependencies$1.apply(Defaults.scala:136)
            at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
            at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
            at sbt.std.Transform$$anon$4.work(System.scala:63)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
    6)
            at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
            at sbt.Execute.work(Execute.scala:235)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
            at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
    tions.scala:159)
            at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
    1)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
    java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
    .java:617)
            at java.lang.Thread.run(Thread.java:745)
    [error] (*:allDependencies) The following features could not be resolved: Set(De
    pendency(aries-blueprint,0.0.0,true,true), Dependency(wrap,0.0.0,true,true), Dep
    endency(log,0.0.0,true,true), Dependency(scr,0.0.0,true,true))
    [error] Total time: 0 s, completed 19-Oct-2015 13:04:41

**Comment by wav** [comment]
The feature cannot be resolved because you removed the dependency for the features repository/descriptor (`FeatureID`) that contains the missing features described in the error.

**Comment by wav** [comment]
Using only the `blueprint.xml` and a minimal `build.sbt`, with no sources yields.

```xml
<features xmlns="http://karaf.apache.org/xmlns/features/v1.3.0" name="base_osgi">
  <repository>mvn:org.apache.karaf.features/standard/4.0.2/xml/features</repository>
  <repository>mvn:org.apache.camel.karaf/apache-camel/2.16.0/xml/features</repository>
  <feature description="base_osgi" version="1.0.0" name="base_osgi">
    <feature dependency="true" prerequisite="true">log</feature>
    <bundle>file:/Users/wassim/base_osgi_bluprint/target/scala-2.11/base_osgi_2.11-1.0.jar</bundle>
    <bundle>mvn:org.scala-lang/scala-library/2.11.7</bundle>
    <feature dependency="true" prerequisite="true">camel-blueprint</feature>
    <feature dependency="true" prerequisite="true">aries-blueprint</feature>
    <feature dependency="true" prerequisite="true">wrap</feature>
  </feature>
</features>
```

```bash
FeaturesServiceImpl  		     |Bundles to install:
FeaturesServiceImpl              |       mvn:org.apache.camel/camel-blueprint/2.16.0
FeaturesServiceImpl              | Installing bundles:
FeaturesServiceImpl              |   mvn:org.apache.camel/camel-blueprint/2.16.0
FeaturesServiceImpl              | Starting bundles:
FeaturesServiceImpl              |   org.apache.camel.camel-blueprint/2.16.0
FeaturesServiceImpl              | Done.
FeaturesServiceImpl              | Adding features: base_osgi/[1.0.0,1.0.0]
FeaturesServiceImpl              | Changes to perform:
FeaturesServiceImpl              |   Region: root
FeaturesServiceImpl              |     Bundles to install:
FeaturesServiceImpl              |       mvn:org.apache.karaf.deployer/org.apache.karaf.deployer.wrap/4.0.2
FeaturesServiceImpl              |       mvn:org.ops4j.pax.url/pax-url-wrap/2.4.3/jar/uber
FeaturesServiceImpl              | Installing bundles:
FeaturesServiceImpl              |   mvn:org.apache.karaf.deployer/org.apache.karaf.deployer.wrap/4.0.2
FeaturesServiceImpl              |   mvn:org.ops4j.pax.url/pax-url-wrap/2.4.3/jar/uber
FeaturesServiceImpl              | Starting bundles:
FeaturesServiceImpl              |   org.ops4j.pax.url.wrap/2.4.3
FeaturesServiceImpl              |   org.apache.karaf.deployer.wrap/4.0.2
FeaturesServiceImpl              | Done.
FeaturesServiceImpl              | Changes to perform:
FeaturesServiceImpl              |   Region: root
FeaturesServiceImpl              |     Bundles to install:
FeaturesServiceImpl              |       file:/Users/wassim/base_osgi_bluprint/target/scala-2.11/base_osgi_2.11-1.0.jar
FeaturesServiceImpl              |       mvn:org.scala-lang/scala-library/2.11.7
FeaturesServiceImpl              | Installing bundles:
FeaturesServiceImpl              |   file:/Users/wassim/base_osgi_bluprint/target/scala-2.11/base_osgi_2.11-1.0.jar
FeaturesServiceImpl              |   mvn:org.scala-lang/scala-library/2.11.7
FeaturesServiceImpl              | Starting bundles:
FeaturesServiceImpl              |   org.scala-lang.scala-library/2.11.7.v20150622-112736-1fbce4612c
FeaturesServiceImpl              |   base_osgi/1.0.0
BlueprintCamelContext            | Apache Camel 2.16.0 (CamelContext: camel-1) is starting
ManagedManagementStrategy        | JMX is enabled
DefaultRuntimeEndpointRegistry   | Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
BlueprintCamelContext            | AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
BlueprintCamelContext            | StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
BlueprintCamelContext            | Route: route1 started and consuming from: Endpoint[timer://test]
BlueprintCamelContext            | Total 1 routes, of which 1 is started.
BlueprintCamelContext            | Apache Camel 2.16.0 (CamelContext: camel-1) started in 0.348 seconds
FeaturesServiceImpl              |  Done.
test                             | Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
test                             | Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
```
Given
```xml
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">
    <camelContext 
        xmlns="http://camel.apache.org/schema/blueprint">
        <route>
            <from uri="timer:test" />
            <to uri="log:test" />
        </route>
    </camelContext>
</blueprint>
```

```scala
featuresRequired := Map(
	"wrap" -> "*",
	"log" -> "*",
	"camel-blueprint" -> "*",
	"aries-blueprint" -> "*")

featuresAddDependencies := true

libraryDependencies ++= Seq(
  FeatureID("org.apache.karaf.features", "standard", "4.0.2"),
  FeatureID("org.apache.camel.karaf", "apache-camel", "2.16.0"),
  "org.osgi" % "org.osgi.core" % "6.0.0" % "provided")
```

It appears that the features are not starting up correctly causing the bundle to be stuck in the `GracePeriod`. I managed to start the bundle by doing the following.

```bash
karaf> feature:uninstall base_osgi
karaf> feature:install camel-core aries-blueprint
karaf> feature:install -s camel-blueprint
karaf> feature:install base_osgi
```

The next thing to work out is whether an appropriate `features.xml` will fix this and potentially change the setting `featuresRequired` so that the `<feature />` attributes can be configured.

**Comment by wav** [comment]
I had a go at this also: https://github.com/PhilAndrew/sbt-osgi-felix-akka-blueprint-camel.git . I think it's failing because bundles are not starting. But we'll address this first.

**Comment by wav** [comment]
The assertion that the features file is bad is correct. I'll change `featuresRequired`.

**Comment by wav** [comment]
The syntax has been slightly modified, see: https://github.com/wav/osgi-tooling/blob/461d6fd97949b3f91ab5c3b1710faa6b6752db72/sbt-karaf/src/sbt-test/devenv/refresh-bundle/build.sbt

Blueprint should start correctly now.

**Comment by PhilAndrew** [comment]
Oh great, so I updated my project based on your example and I've got a thing at the bottom of the build.sbt which removes things from the features.xml file at the end.  Basically because of Akka.

https://github.com/PhilAndrew/base_osgi

Is there any other way I can declare that these shouldn't be in the features.xml?

**Comment by wav** [comment]
Use the transitivity rules is sbt. See http://www.scala-sbt.org/0.13/docs/Library-Management.html .

Anything in the `compile` scope will be added to the feature. Have a look at the PR I made previously.

**Comment by PhilAndrew** [comment]
Thanks, so my projects working now with Akka and Camel and its ok ... mostly. Also this one does Camel https://github.com/PhilAndrew/sbt-osgi-felix-akka-blueprint-camel, I need to integrate Akka/Camel on this.

The important thing is that I have a base osgi project which does Akka, Camel and it seems stable and works on Karaf or maybe Felix.

**Comment by wav** [comment]
Cool. I'll have a look at the other one this weekend and see if I can suss it out if you don't get to it first.

Before closing this issue. I see you try and modify the features file. Is that really necessary?

I think that this project should complement `sbt-osgi-felix` when you want to deploy a set of bundles to Karaf.

**Comment by PhilAndrew** [comment]
Hi, not in answer to your question but I wanted to share with you what I found with the Felix project. I implemented the Camel Akka etc here: https://github.com/PhilAndrew/sbt-osgi-felix-akka-blueprint-camel

I like that I can just sbt run and also Felix doesn't seem to get into a bad state and crash and go crazy like Karaf sometimes forcing me to re-install Karaf.  Also Felix seems to be more OSGi standard, your just putting jars into a OSGi container rather than relying on a features.xml

What I don't like is that there's no equivalent of Karaf features, Felix bundle requires all the JAR's for the thing to work where-as Karaf will download the dependant jars based upon the features file.

Overall, the Felix way is more comfortable to program in as I can just sbt run and I don't get headaches, but the Karaf way makes more sense for dynamic re-deployments as you have written it.

Any ideas/suggestions/correct my mis-understandings?

Also I want to point out you can "technically" embed Karaf inside a Java app so it could be run from sbt run as Karaf embedded.

**Comment by PhilAndrew** [comment]
In answer to your question, I don't need that code which deleted things from features.xml post your generation of the file, it works fine without my delete of feature.

**Comment by wav** [comment]
Thanks for sharing I'm keen to see your progress.

Karaf provides an OSGi runtime (e.g. Felix by default) and a bunch of components like logging and 
deployers (which is what allows dynamic re-deployments) and a standard way of organising an application. Out of the box, it's like an app container.

Yes, you can trim Karaf down to just starting the runtime, I was considering this until I saw `sbt-osgi-felix` which effectively does that.

The `woq-blended` project has also recognised this and it looks like they've built their own runner that can be bootstrapped with bundles, karaf features and karaf (?) profiles described as "HOCON" (think typesafe config) instead of XML but I haven't got around to using it.

In relation to this project I was thinking generating the features based on what is resolved `sbt-osgi-felix` but haven't put much thought into it.
