### ISSUE TITLE
Trouble building, will investigate

### ISSUE THREAD

**Issue by PhilAndrew** [wav/osgi-tooling#4]
G:\home\projects\universe\browser\application\util\osgi-tooling>sbt update compi
le
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
[info] Loading project definition from G:\home\projects\universe\browser\applica
tion\util\osgi-tooling\project
[info] Set current project to osgitools (in build file:/G:/home/projects/univers
e/browser/application/util/osgi-tooling/)
[info] Updating {file:/G:/home/projects/universe/browser/application/util/osgi-t
ooling/}osgi-tooling...
[info] Updating {file:/G:/home/projects/universe/browser/application/util/osgi-t
ooling/}karaf-mbean-wrapper...
[info] Updating {file:/G:/home/projects/universe/browser/application/util/osgi-t
ooling/}sbt-karaf...
[info] Updating {file:/G:/home/projects/universe/browser/application/util/osgi-t
ooling/}sbt-karaf-packaging...
[info] Resolving org.apache.karaf.features#org.apache.karaf.features.core;4.0.0
[info] Resolving org.apache.karaf.instance#org.apache.karaf.instance.core;4.0.0
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Done updating.
[info] Done updating.
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07
[info] Resolving org.apache#apache;14 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.sisu#org.eclipse.sisu.plexus;0.3.0.M1: several problems o
ccurred while resolving dependency: org.eclipse.sisu#org.eclipse.sisu.plexus;0.3
.0.M1 {compile=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.eclipse.sisu#s
isu-plexus;0.3.0.M1 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  :: org.eclipse.aether#aether-impl;1.0.1.v20141111: several problems occu
rred while resolving dependency: org.eclipse.aether#aether-impl;1.0.1.v20141111
{compile=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.eclipse.aether
#aether;1.0.1.v20141111 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  :: org.eclipse.aether#aether-connector-basic;1.0.1.v20141111: several pr
oblems occurred while resolving dependency: org.eclipse.aether#aether-connector-
basic;1.0.1.v20141111 {compile=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.eclipse.aether
#aether;1.0.1.v20141111 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  :: org.apache.maven#maven-aether-provider;3.2.3: several problems occurr
ed while resolving dependency: org.apache.maven#maven-aether-provider;3.2.3 {com
pile=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.apache.maven#m
aven;3.2.3 {}:
[warn]  several problems occurred while resolving dependency: org.apache.maven#m
aven-parent;24 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.apache.karaf#karaf;4.0.0 ...
[error] Server access Error: Connection timed out: connect url=https://repo.scal
a-sbt.org/scalasbt/sbt-plugin-releases/org.apache.karaf.assemblies/assemblies/4.
0.0/ivys/ivy.xml
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.karaf.features#standard;4.0.0: several problems occurred w
hile resolving dependency: org.apache.karaf.features#standard;4.0.0 {compile=[de
fault(compile)]}:
[warn]  several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies.features#features;4.0.0 {}:
[warn]  several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies#assemblies;4.0.0 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.apache.karaf#karaf;4.0.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.karaf.features#enterprise;4.0.0: several problems occurred
 while resolving dependency: org.apache.karaf.features#enterprise;4.0.0 {compile
=[default(compile)]}:
[warn]  several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies.features#features;4.0.0 {}:
[warn]  several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies#assemblies;4.0.0 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.ops4j#master;4.2.0 ...
[error] Server access Error: Connection timed out: connect url=https://repo.scal
a-sbt.org/scalasbt/sbt-plugin-releases/org.ops4j/master/4.2.0/ivys/ivy.xml
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.ops4j.pax.web#pax-web-features;4.1.4: several problems occurred w
hile resolving dependency: org.ops4j.pax.web#pax-web-features;4.1.4 {compile=[de
fault(compile)]}:
[warn]  several problems occurred while resolving dependency: org.ops4j.pax#web;
4.1.4 {}:
[warn]  several problems occurred while resolving dependency: org.ops4j#master;4
.2.0 {}:
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]
[warn]  java.lang.IllegalArgumentException: protocol = http host = null
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.0.M1
[warn]            +- org.scala-sbt:sbt-maven-resolver:0.13.9 (scalaVersion=2.10,
 sbtVersion=0.13) ((sbt.BuildExtra) Defaults.scala#L1821)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.eclipse.aether:aether-impl:1.0.1.v20141111
[warn]            +- org.scala-sbt:sbt-maven-resolver:0.13.9 (scalaVersion=2.10,
 sbtVersion=0.13) ((sbt.BuildExtra) Defaults.scala#L1821)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.eclipse.aether:aether-connector-basic:1.0.1.v20141111
[warn]            +- org.scala-sbt:sbt-maven-resolver:0.13.9 (scalaVersion=2.10,
 sbtVersion=0.13) ((sbt.BuildExtra) Defaults.scala#L1821)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.apache.maven:maven-aether-provider:3.2.3
[warn]            +- org.scala-sbt:sbt-maven-resolver:0.13.9 (scalaVersion=2.10,
 sbtVersion=0.13) ((sbt.BuildExtra) Defaults.scala#L1821)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.apache.karaf.features:standard:4.0.0 (G:\home\projects\unive
rse\browser\application\util\osgi-tooling\sbt-karaf-packaging\build.sbt#L30-31)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.apache.karaf.features:enterprise:4.0.0 (G:\home\projects\uni
verse\browser\application\util\osgi-tooling\sbt-karaf-packaging\build.sbt#L30-31
)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
[warn]          org.ops4j.pax.web:pax-web-features:4.1.4 (G:\home\projects\unive
rse\browser\application\util\osgi-tooling\sbt-karaf-packaging\build.sbt#L30-31)
[warn]            +- wav.devtools:sbt-karaf-packaging:0.1-SNAPSHOT (scalaVersion
=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.eclipse.sisu#org.eclipse.sisu.p
lexus;0.3.0.M1: several problems occurred while resolving dependency: org.eclips
e.sisu#org.eclipse.sisu.plexus;0.3.0.M1 {compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.eclipse.sisu#s
isu-plexus;0.3.0.M1 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.eclipse.aether#aether-impl;1.0.1.v20141111: several p
roblems occurred while resolving dependency: org.eclipse.aether#aether-impl;1.0.
1.v20141111 {compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.eclipse.aether
#aether;1.0.1.v20141111 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.eclipse.aether#aether-connector-basic;1.0.1.v20141111
: several problems occurred while resolving dependency: org.eclipse.aether#aethe
r-connector-basic;1.0.1.v20141111 {compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.eclipse.aether
#aether;1.0.1.v20141111 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.apache.maven#maven-aether-provider;3.2.3: several pro
blems occurred while resolving dependency: org.apache.maven#maven-aether-provide
r;3.2.3 {compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.apache.maven#m
aven;3.2.3 {}:
        several problems occurred while resolving dependency: org.apache.maven#m
aven-parent;24 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.apache.karaf.features#standard;4.0.0: several problem
s occurred while resolving dependency: org.apache.karaf.features#standard;4.0.0
{compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies.features#features;4.0.0 {}:
        several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies#assemblies;4.0.0 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.apache.karaf.features#enterprise;4.0.0: several probl
ems occurred while resolving dependency: org.apache.karaf.features#enterprise;4.
0.0 {compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies.features#features;4.0.0 {}:
        several problems occurred while resolving dependency: org.apache.karaf.a
ssemblies#assemblies;4.0.0 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

unresolved dependency: org.ops4j.pax.web#pax-web-features;4.1.4: several problem
s occurred while resolving dependency: org.ops4j.pax.web#pax-web-features;4.1.4
{compile=[default(compile)]}:
        several problems occurred while resolving dependency: org.ops4j.pax#web;
4.1.4 {}:
        several problems occurred while resolving dependency: org.ops4j#master;4
.2.0 {}:
        java.lang.IllegalArgumentException: protocol = http host = null
        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

        java.lang.IllegalArgumentException: protocol = http host = null

        at sbt.ivyint.CachedResolutionResolveEngine$class.mergeErrors(CachedReso
lutionResolveEngine.scala:360)
        at sbt.IvySbt$$anon$5$$anon$3.mergeErrors(Ivy.scala:101)
        at sbt.ivyint.CachedResolutionResolveEngine$class.mergeResults(CachedRes
olutionResolveEngine.scala:347)
        at sbt.IvySbt$$anon$5$$anon$3.mergeResults(Ivy.scala:101)
        at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.app
ly(CachedResolutionResolveEngine.scala:336)
        at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.app
ly(CachedResolutionResolveEngine.scala:286)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:
189)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:632
)
        at sbt.ivyint.CachedResolutionResolveCache.getOrElseUpdateProjectReport(
CachedResolutionResolveEngine.scala:244)
        at sbt.ivyint.CachedResolutionResolveEngine$class.customResolve(CachedRe
solutionResolveEngine.scala:286)
        at sbt.IvySbt$$anon$5$$anon$3.customResolve(Ivy.scala:101)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:178)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRet
ries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:
97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala
:1392)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala
:1388)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1
422)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1
420)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (sbt-karaf-packaging/*:update) sbt.ResolveException: unresolved dependen
cy: org.eclipse.sisu#org.eclipse.sisu.plexus;0.3.0.M1: several problems occurred
 while resolving dependency: org.eclipse.sisu#org.eclipse.sisu.plexus;0.3.0.M1 {
compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.eclips
e.sisu#sisu-plexus;0.3.0.M1 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.eclipse.aether#aether-impl;1.0.1.v20141111: s
everal problems occurred while resolving dependency: org.eclipse.aether#aether-i
mpl;1.0.1.v20141111 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.eclips
e.aether#aether;1.0.1.v20141111 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.eclipse.aether#aether-connector-basic;1.0.1.v
20141111: several problems occurred while resolving dependency: org.eclipse.aeth
er#aether-connector-basic;1.0.1.v20141111 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.eclips
e.aether#aether;1.0.1.v20141111 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.apache.maven#maven-aether-provider;3.2.3: sev
eral problems occurred while resolving dependency: org.apache.maven#maven-aether
-provider;3.2.3 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.apache
.maven#maven;3.2.3 {}:
[error]         several problems occurred while resolving dependency: org.apache
.maven#maven-parent;24 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.apache.karaf.features#standard;4.0.0: several
 problems occurred while resolving dependency: org.apache.karaf.features#standar
d;4.0.0 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.apache
.karaf.assemblies.features#features;4.0.0 {}:
[error]         several problems occurred while resolving dependency: org.apache
.karaf.assemblies#assemblies;4.0.0 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.apache.karaf.features#enterprise;4.0.0: sever
al problems occurred while resolving dependency: org.apache.karaf.features#enter
prise;4.0.0 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.apache
.karaf.assemblies.features#features;4.0.0 {}:
[error]         several problems occurred while resolving dependency: org.apache
.karaf.assemblies#assemblies;4.0.0 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error] unresolved dependency: org.ops4j.pax.web#pax-web-features;4.1.4: several
 problems occurred while resolving dependency: org.ops4j.pax.web#pax-web-feature
s;4.1.4 {compile=[default(compile)]}:
[error]         several problems occurred while resolving dependency: org.ops4j.
pax#web;4.1.4 {}:
[error]         several problems occurred while resolving dependency: org.ops4j#
master;4.2.0 {}:
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error]
[error]         java.lang.IllegalArgumentException: protocol = http host = null
[error] Total time: 153 s, completed 01-Sep-2015 12:55:29

G:\home\projects\universe\browser\application\util\osgi-tooling>

**Comment by PhilAndrew** [comment]
Deleted my ivy2 and sbt caches, can build now, sorry, just ignore this.
